blank_issues_enabled: false
contact_links:
  - name: Question?
    url: https://github.com/coil-kt/coil/discussions
    about: Please ask usage questions in Github Discussions or Stack Overflow - not in Issues.
